### ISSUE TITLE
2D Projection?

### ISSUE THREAD

**Issue by notflip** [uber/h3-js#102]
This lib is working fine but there's a (to be expected) distortion, is there a simple way to represent the hexagons in a flat 2D way?

**Comment by nrabinowitz** [comment]
That's an interesting question, and it depends on your use case. The underlying representation of the grid does not have distortion, but this grid is projected (via inverse gnomonic projection, see [some explanation here](https://h3geo.org/docs/core-library/h3ToGeoDesc)) to get the lat/long coords for each cell. This creates the distortion you describe. However, you can reverse the transformation when rendering with a gnomonic projection, as demonstrated here: https://observablehq.com/@nrabinowitz/flat-h3-grid-via-gnomonic-projection

This only works if you have control over the projection of your map, of course, and only when all the cells you want to render are on the same icosahedron face.
