### ISSUE TITLE
Inconsistent results from polyfill after calling polyfill with complex polygon crossing antimeridian

### ISSUE THREAD

**Issue by pugsley** [uber/h3-js#103]
It seems that calling `polyfill` with a complex polygon (that crosses the antimeridian) messes with the h3 internals somehow, causing subsequent calls to return incorrect results.

This is best demonstrated by this jsfiddle: https://jsfiddle.net/tamaxerra/kxz865m7/1/

The console output from the fiddle is the number of h3 indexes returned:
```
36
56
27
```

The first (36) and last (27) count are the result of the same polygon being passed.

**Comment by nrabinowitz** [comment]
I can reproduce this in Observable as well, though it's less deterministic 😢. Cannot repro in `h3-py`, which makes me think this is JS-specific, probably due to something in Emscripten. Will investigate.

**Comment by nrabinowitz** [comment]
Thanks for bringing this up! This was a problem with the JS binding, fix currrently in review.

**Comment by pugsley** [comment]
Thanks, really appreciate the speedy fix! 👍

**Comment by nrabinowitz** [comment]
Thank you for the easy repro scenario! This would have been very difficult to debug without a deterministic reproduction.
