### ISSUE TITLE
Export the JS tutorials as plain Javascript

### ISSUE THREAD

**Issue by 2xlbu4u** [uber/h3-js#112]
Extracting the h3 code from the Observables workbooks has been brutal. All my existing code uses jQuery so having just plain HTML, Javascript examples would save a lot of time

**Comment by nrabinowitz** [comment]
I'm willing to include some examples in the library, but they'd probably be just JS - I don't think it makes sense to add HTML with a map or other visualization, as those are not part of the library and would likely vary widely between consumers. What examples are you looking for that aren't easy to extract from Observable?

**Comment by 2xlbu4u** [comment]
Nick,

Thanks for the response.

Once putting it through a beautifier, I was able to extract the parts that
build and manipulate the layers so I'm all set.
I'm not used to E6 level JS so it was difficult at first.

Regards
-John

**Comment by nrabinowitz** [comment]
OK, closing this for now if this is primarily about usage in maps - there are lots of different approaches here, and I don't think including them in this repo is the right move, as they'd be hard to test and keep up to date.
