### ISSUE TITLE
h3js index find all children using index values

### ISSUE THREAD

**Issue by am2222** [uber/h3-js#122]
Hello, 
 Suppose we are storing h3 indexes in a database column. To perform a parent/child query I was thinking of using h3 indexes. Lets say we have this index `832834fffffffff`. This cell's children are`[  '8428341ffffffff',  '8428343ffffffff',  '8428345ffffffff',  '8428347ffffffff',  '8428349ffffffff',  '842834bffffffff',  '842834dffffffff']`.  What is the logic to tell if an h3index id is a child of another id. Is there any way that we can find a range of indexies that are child of the specific id. 
I already found https://github.com/uber/h3/issues/320 and https://stackoverflow.com/questions/53911322/is-the-h3index-ordered but could not find my answer.
Thanks

**Comment by dfellis** [comment]
So the following snippet ought to work:

```js
function isChildOf(possibleParent, possibleChild) {
  return possibleParent === h3.h3ToParent(possibleChild, h3.h3GetResolution(possibleParent));
}
```

Since the parent-child relationship is a simple tree structure in H3, there can be only one parent for any H3 index at any given resolution coarser (smaller) than its own resolution.

**Comment by dfellis** [comment]
Oh, and the second piece "find a range of indexes that are all children of a specified id" is just `h3.h3ToChildren(index, childResolution)`

**Comment by am2222** [comment]
@dfellis thanks for the reply. But since we don't have access to the h3 library in the database is there any equations or logic to calculate the output of `h3.h3ToChildren(index, childResolution)` in database?

**Comment by dfellis** [comment]
So, yes, the underlying C implementation of `h3ToParent` and `h3ToChildren` is *relatively* straitghtforward (parent is much easier than children, though).

[`h3ToParent`](https://github.com/uber/h3/blob/v3.7.1/src/h3lib/lib/h3Index.c#L144-L158) is some sanity checking up front, and then some bit masking to replace the resolution with the new parent resolution and write `1`s to all of the bits for the resolutions that are larger than that.

[`h3ToChildren`](https://github.com/uber/h3/blob/v3.7.1/src/h3lib/lib/h3Index.c#L220-L243) has to allocate memory for the maximum number of children possible at that child level, then it loops through the possible children with special logic to detect and handle "missing children" if one of the indexes is actually a pentagon, and writes them into the allocated memory. This one would be hard to replicate in a database, but not impossible.

**Comment by am2222** [comment]
@dfellis Thanks, I am looking into the functions. it seems they are the exact functions I am looking for
