### ISSUE TITLE
License advice

### ISSUE THREAD

**Issue by obrl-soil** [uber/h3-js#123]
Hi, just seeking some advice on how to correctly attribute the license for https://github.com/obrl-soil/h3jsr.

I've inherited Apache 2.0 from this project, with the attribution statement split per https://github.com/obrl-soil/h3jsr/blob/master/LICENSE.md#appendix-how-to-apply-the-apache-license-to-your-work. Is this the correct approach?

I should note your own copy of the license is still blank at  https://github.com/uber/h3-js/blob/6b34d6c8c2fe2290b44df2d9d34bcffbae1491bd/LICENSE#L189

**Comment by nrabinowitz** [comment]
IANAL, so please don't take my response as legal advice, but:

- You are *not* required to use the Apache license. As I understand it, you are creating new software that you may license as you wish.
- You do however ship `h3-js` code as part of your software. I would suggest including the original Apache license from `h3-js` (well, after I fix it to include Uber attribution 🤦 ) in the directory with the redistributed code.
- You could also include a line in your license (whichever license you use), e.g.

```
This project includes code from the h3-js project, copyright 2017 Uber Technologies, Inc.
```
with a link to the license file (probably the file you're including in your own code), and possibly a short reference to the license. See e.g. the [Apache Arrow license](https://github.com/apache/arrow/blob/master/LICENSE.txt#L324) for examples of including license notices for embedded code in your project.

> I should note your own copy of the license is still blank at
> 
> https://github.com/uber/h3-js/blob/6b34d6c8c2fe2290b44df2d9d34bcffbae1491bd/LICENSE#L189

Good catch, thank you :).

**Comment by obrl-soil** [comment]
Ah, cool. Between that and the advice at https://r-pkgs.org/license.html I think I can muddle through. Thanks!
