### ISSUE TITLE
Growing memory usage

### ISSUE THREAD

**Issue by johanschram** [uber/h3-js#128]
Hi, 

I'm using h3-js to compile isochrones (a few hundred millions), and I notices that the memory usage keep growing. After some quick investigations on my code to make sure the issue is not on my side, I think this comes from either h3SetToMultiPolygon or multiPolyfill (I investigate a while ago, and I can't remember). Anyway, after it does what it is supposed to do, a small amont of memory keep being used, and thus, after running it a couple of thousand times, node runs out of memory.
For now, as a quick dirty fix, I run it on child processes that I can restart once in a while. 

Sorry for not providing more intels, I investigate this a while ago and found a quick workaround, but it still worth sharing the issue.

Note: i'm using 3.7.1

EDIT: version 3.7.1 was apparently supposed to fix this issue. I guess it's still there...

**Comment by nrabinowitz** [comment]
Do you have a reproducible case we can test with here? We did have an earlier memory issue we believe to be fixed, around `polyfill`. On the Emscripten size, there's a fixed memory limit, so I believe running a bad case repeatedly should eventually error out with Emscripten's version of OOM - so all we need is an example of something bad that we can run millions of times.

**Comment by johanschram** [comment]
I don't have anything to provide right now, but I'll see what I can do in a couple of days. For sure, bad cases are not so inusual, or at least with the polygons I treat: I generally run 10 to 20 parallel node child processes, and the memory foot print tend to follow the same slowly rising curve.

**Comment by nrabinowitz** [comment]
OK, I can take a look. Does this give you an OOM error? or do you just see the memory rising in system monitors?

**Comment by johanschram** [comment]
Both, memory is rising and depending on how much memory is given to node, eventually you will get an OOM error.

**Comment by nrabinowitz** [comment]
OK, but currently this is a Node OOM, not an Emscripten OOM. That's interesting, Emscripten has a dedicated amount of memory for its internal "heap" and should throw it's own OOM error well before Node runs out of memory. That suggests this might be on the JS side. I can try to do some tests today.

**Comment by nrabinowitz** [comment]
I am not able to repro this. I ran the code above and charted the memory output using `process.memoryUsage()`. I see the expected sawtooth - memory ramping up, then getting garbage collected and going down. The bottom of the graph seems to stay pretty stable at 4.5Mb.
```
[4999] memoryUsage: 17777 / 38568 kB | max 20590 kB

   20590.00 ┤  ╭╮   ╭╮           ╭╮   ╭╮           ╭╮   ╭╮           ╭╮   ╭╮           ╭╮   ╭╮           ╭╮   ╭╮           ╭╮   ╭╮   
   17989.67 ┤  ││ ╭╮││ ╭╮   ╭╮   ││ ╭╮││ ╭╮   ╭╮   ││ ╭╮││ ╭╮   ╭╮   ││ ╭╮││ ╭╮   ╭╮   ││ ╭╮││ ╭╮   ╭╮   ││ ╭╮││ ╭╮   ╭╮   ││ ╭╮││ ╭ 
   15389.33 ┤╭╮││ ││││ ││ ╭╮││ ╭╮││ ││││ ││ ╭╮││ ╭╮││ ││││ ││ ╭╮││ ╭╮││ ││││ ││ ╭╮││ ╭╮││ ││││ ││ ╭╮││ ╭╮││ ││││ ││ ╭╮││ ╭╮││ ││││ │ 
   12789.00 ┤│││╰╮│││╰╮││ │││╰╮│││╰╮│││╰╮││ │││╰╮│││╰╮│││╰╮││ │││╰╮│││╰╮│││╰╮││ │││╰╮│││╰╮│││╰╮││ │││╰╮│││╰╮│││╰╮││ │││╰╮│││╰╮│││╰╮│ 
   10188.67 ┤│╰╯ ││╰╯ ││╰╮│╰╯ ││╰╯ ││╰╯ ││╰╮│╰╯ ││╰╯ ││╰╯ ││╰╮│╰╯ ││╰╯ ││╰╯ ││╰╮│╰╯ ││╰╯ ││╰╯ ││╰╮│╰╯ ││╰╯ ││╰╯ ││╰╮│╰╯ ││╰╯ ││╰╯ ││ 
    7588.33 ┤│   ╰╯   ╰╯ ││   ││   ╰╯   ╰╯ ││   ││   ╰╯   ╰╯ ││   ││   ╰╯   ╰╯ ││   ││   ╰╯   ╰╯ ││   ││   ╰╯   ╰╯ ││   ││   ╰╯   ╰╯ 
    4988.00 ┼╯           ╰╯   ╰╯           ╰╯   ╰╯           ╰╯   ╰╯           ╰╯   ╰╯           ╰╯   ╰╯           ╰╯   ╰╯           
```
This shows high memory usage, but I don't see a leak, and I went over the code and don't see leak suspects (though this is a particularly hairy part of the code w/r/t memory management). I used Node `v14.16.1`.

What Node version are you using? And does the isolated example above throw an OOM for you? We're definitely using a lot of memory here, and you could likely reduce it by e.g. splitting up the polygons or using a coarser hex and then uncompacting it to a finer resolution, but I'm not sure I see a leak.

**Comment by nrabinowitz** [comment]
Closing as I was never able to repro. Please reopen if there's a repeatable scenario.
