### ISSUE TITLE
How to apply h3 to different planets / spheroids?

### ISSUE THREAD

**Issue by lancejpollard** [uber/h3-js#129]
I have this current question on StackOverflow, not sure if anyone will answer this GIS-related question there, so linking here:

[Where is the origin that maps the base hexagons in Uber's H3 Hexagonal hierarchical geospatial indexing system to the globe?](https://stackoverflow.com/questions/70700672/where-is-the-origin-that-maps-the-base-hexagons-in-ubers-h3-hexagonal-hierarchi)

Basically, the first question is, where is the data/internal-code that actually maps the hexagons to the Earth's surface to specific lat/lng coordinates for each tile?

That leads me to the main question, which is, how would you go about applying this same system to a different planet or spheroid like the moon or Jupiter, or the sun? I would need to somehow project the 122 tiles onto the spheroid... Oh wow I am already lost, I am pretty sure that is what the core of what H3 does internally. But the question is how do you plugin a different sized planet or something, and how do I say "this tile is right here on the moon", etc.? I would like to traverse the hex tiles at a specific resolution on the moon, knowing that the projection is firmly planted permanently on the surface of the moon basically, not sure how that would work.

**Comment by nrabinowitz** [comment]
See [this related answer](https://stackoverflow.com/a/68673828/380487). The main issues are: 
- Orientation of the icosahedron (you may not care, depending on the use case)
- Distance and area measurements, which are based on the Earth radius

The easiest, and likely best, option if you need to change these is to transform the results, rather than trying to change anything in the H3 internals.

**Comment by lancejpollard** [comment]
Can you explain what you mean by transform the results? What is an example?

**Comment by nrabinowitz** [comment]
> Interesting, okay well would you be able to explain what you mean by transform the results? What is an example?

- For distance functions, use the radian-based output (e.g. `exactEdgeLengthRads`) and multiply by the desired spherical radius
- For area functions, use the radian-based output (e.g. `cellAreaRads2`) and multiply by the desired spherical radius squared
- For orientation, you'd need to transform all lat/lng output with some rotation. The H3 grid is based on a spherical model, so you'd just need to rotate the coordinates by some amount (add a lat offset to lat, a lng offset to lng, and handle the poles and anti-meridian). You may not need this unless it matters to you whether the grid system is e.g. pole-aligned. [This paper](http://webpages.sou.edu/~sahrk/sqspc/pubs/gdggs03.pdf) has some discussion of alternate orientations.
