### ISSUE TITLE
how can i detect a coordinate (point) inside hexagon

### ISSUE THREAD

**Issue by abilican** [uber/h3-js#132]
Hi,
I know there are many different ways to find that a coordinate is inside a hexagon or not but. I searched in h3js but couldn't find. Do you suggest any way that you used before with h3js? 
If I find exactly work a solution, i'll write here.

**Comment by dfellis** [comment]
Inside an H3-defined hexagon or any arbitrary hexagon on the planet?

H3 is a grid system, so arbitrary hexagons not aligned with its grid won't work, and you should use a "point-in-poly" library to do this along with the hexagon in question.

If it is an H3 hexagon, you can just run `geoToH3` at the same resolution as your current H3 hexagon and just check if the IDs are identical or not.

**Comment by abilican** [comment]
Yes, it's h3 hexegon, as you said, just compering h3Indexes enought for know coordinate is in hexagon. it's my fault, I approached to problem from a geometric perspective.
Thanks so much @dfellis.
