### ISSUE TITLE
Where does h3-js use DGGRID?

### ISSUE THREAD

**Issue by mircowidmer** [uber/h3-js#133]
In the `README.md` it says 

> DGGRID Copyright (c) 2015 Southern Oregon University

DGGRID is licensed under AGPL, but h3-js is licensed under Apache License 2.0.
Which functions of DGGRID are used by h3-js and is it a problem, that DGGRID is licensed under AGPL?

Within https://github.com/uber/h3/blob/787eb2e97f73c85c9199774b0397a6bb459cc647/src/h3lib/lib/coordijk.c I found a reference to DGGRID:

> /**
>  * Determine the containing hex in ijk+ coordinates for a 2D cartesian
>  * coordinate vector (from DGGRID).
>  *
>  * @param v The 2D cartesian coordinate vector.
>  * @param h The ijk+ coordinates of the containing hex.
>  */
> void _hex2dToCoordIJK(const Vec2d *v, CoordIJK *h) {

Is it the case, that the method `_hex2dToCoordIJK` has been copied from _DGGRID_ and therefore the license reference to _DGGRID_ exists?

**Comment by nrabinowitz** [comment]
This is discussed here:
https://github.com/uber/h3/issues/531
https://github.com/uber/h3/issues/28

The `h3-js` project itself does not use DGGRID directly, but some code in the H3 library was based on DGGRID at a time when DGGRID was in the public domain. We keep the copyright notice but there are no licensing implications.

**Comment by mircowidmer** [comment]
Thank you very much! 👍
