### ISSUE TITLE
How to get congestion H3 for a city or area?

### ISSUE THREAD

**Issue by MshadDr** [uber/h3-js#145]
Hi i want to know does it possible to figure out if a H3 in crowded or not?

**Comment by nrabinowitz** [comment]
The H3 library itself doesn't have any data about what's in each cell. If you just want population, you could look at https://dataforgood.facebook.com/dfg/tools/high-resolution-population-density-maps or https://data.humdata.org/dataset/kontur-population-dataset (indexed by H3 res 8).
