### ISSUE TITLE
Openlayers instead of Mapbox

### ISSUE THREAD

**Issue by sharmapn** [uber/h3-js#160]
I was hoping to use Openlayers mapping feature instead pf Mapbox.
Is it possible?

**Comment by nrabinowitz** [comment]
The `h3-js` library has no dependency on any mapping library - it just works with the H3 grid. I don't have any examples pre-built with OpenLayers, but it should be straightforward to generate GeoJSON with H3 ([geojson2h3](https://github.com/uber/geojson2h3) might help) and pass it to the mapping library.
