### ISSUE TITLE
Integrating with google maps

### ISSUE THREAD

**Issue by ismaildkc** [uber/h3-js#166]
Is there a way to use this library with google maps?

**Comment by nrabinowitz** [comment]
The `h3-js` library is agnostic to mapping libraries you might use. In general, the easiest way to render H3 cells is to use `cellToBoundary` (`h3ToGeoBoundary` in v3) to get each cell as a polygon, then encode this as GeoJSON or a similar standard format and load that in your map (which could be a web map like Leaflet or MapboxGL, or an application like QGIS, or some other rendering library).

* You can see rendering approaches using MapboxGL in the [H3 tutorials on Observable](https://observablehq.com/collection/@nrabinowitz/h3-tutorial)
* You can use the [geojson2h3](https://github.com/uber/geojson2h3) library to more easily convert between H3 and GeoJSON
