### ISSUE TITLE
Load and Display H3-JS binned dataset in Mapbox

### ISSUE THREAD

**Issue by sharmapn** [uber/h3-js#173]
Hello,

I have a website that uses h3-js to bin the points. Then I call a function that counts the number of points in each of the hexagons after the binning and embeds these as attributes within the geoJSON. See https://github.com/uber/h3-js/issues/162
Then I save the geoJSON to disk.

Now, I would like add a feature on my website that allows a user (who has received the binned dataset) to load the binned geoJSON and display the binned points in a mapbox (or Openlayers) map canvas. I was not able to find an example on the web that allows mapbox read the binned data from the geojosn and display it on a mapbox canvas. 

Any assistance on this would be greatly appreciated.

**Comment by nrabinowitz** [comment]
I'm afraid this isn't really an H3 question, if I understand correctly - at this point, you've already done the H3 work and you just need to show GeoJSON data on a Mapbox map with values in the GeoJSON properties. This isn't really the right forum for this question - I'd suggest asking on StackOverflow or in a Mapbox help forum.
