### ISSUE TITLE
H3-JS binning resoluion in OpenLayers

### ISSUE THREAD

**Issue by sharmapn** [uber/h3-js#177]
I am focusing on this example: https://observablehq.com/@nrabinowitz/h3-tutorial-using-point-layers?collection=@nrabinowitz/h3-tutorial. I have implemented this h3-js example in openlayers in my front end application without any nodejs. Example is here https://jsbin.com/nosoyonemi/edit?html,output 

The above jsbin example was in response to create a openlayers version of this mapbox example: https://gis.utah.gov/developer/applications/suitability/ and https://github.com/agrc/gis.utah.gov/tree/master/developer/applications/suitability

However, I would like the user to choose the h3 resolution also, i.e. the SIZE of the hexagons - just as the option given in the original observablehq example. On the observablehq example's page, on the right, three dots, there is an option to Export and Download Code. However, after going through the code, I have not been able to find the code that changes the h3 resolution as per slider value.

The jsbin example provides similar functionality, but is missing the essential feature of allowing the user to choose the h3-resolution, i.e. the size of the hexagons. Instead, the example focuses on aggregating the number of points in the chosen layers. I would be glad if someone could guide me on how to proceed, as I could not find any resources online.

**Comment by nrabinowitz** [comment]
The JSbin example looks good! But this isn't really an h3-js issue, just a web programming issue. You have a `config` object that hard-codes the `h3Resolution` to 8. You just need to add another slider or other input that allows the user to set this value and recalculate the rest of the data based on that change. StackOverflow might be a better place to ask than this repo.
