### ISSUE TITLE
Error when passing zero area polygon to h3.polygonToCells

### ISSUE THREAD

**Issue by pugsley** [uber/h3-js#181]
Not the end of the world because it's easy to code around, but maybe an empty array should be returned?

e.g.
```
h3.polygonToCells([
    [0, 0],
    [0, 90],
    [0, 90],
    [0, 0],
], 1);
```

Results in the follow error:
```
The operation failed but a more specific error is not available (code: 1)
```

**Comment by kbajori50** [comment]
const h3 = require('h3-js');
const turf = require('@turf/turf');
const zeroAreaPolygon = [
    [0, 0],
    [0, 90],
    [0, 90],
    [0, 0],
];
const geojson = turf.polygon([zeroAreaPolygon]);
const area = turf.area(geojson);
if (area === 0) {
    console.log('Zero area polygon, skipping');
    // This is a weird case, why would you have a zero area polygon?
} else {
    // Pass the polygon to h3.polygonToCells
    const cells = h3.polygonToCells(zeroAreaPolygon, 1);
    console.log(cells);
    // This should give you an array of hexagonal cells that cover the polygon
}
