### ISSUE TITLE
Does h3-js send any data to the server? 

### ISSUE THREAD

**Issue by sharmapn** [uber/h3-js#182]
Hello,

I was wondering if while using H3-js, does any of the data (dataset points) gets sent to the server?
Am asking this because there is few JS libraries that are requested.

Our MapSafe website presents a complete tool for achieving geospatial data sovereignty". 
H3-Biining is a data anonymization technique used in the tool and I just wanted to be sure no data gets sent from the website.

I have added these libraries. The first library is stored within the website, in a directory.
```
<!-- h3binning -->
    <script src="assets/js/geojson2h3.js"></script>	<!-- geojson2h3 created using browserify  -->
    <script src="https://unpkg.com/h3-js"></script>
    <script src="https://unpkg.com/h3-js@3.7.2/dist/h3-js.umd.js">
</script>
```
The tool is at https://www.mapsafe.xyz/
The paper published at the TGIS Journal recently: https://onlinelibrary.wiley.com/doi/epdf/10.1111/tgis.13094 (pdf)

There is a video each that demonstrates the use of safeguarding and verification aspects:

- https://www.mapsafe.xyz/safeguarding-guide.html 
- https://www.mapsafe.xyz/verification-guide.html

**Comment by nrabinowitz** [comment]
No, h3-js does not interact on its own with any server, it's fully self-contained. That's true for most (though admittedly not all) JS libraries.
