### ISSUE TITLE
h3-js functions as user-defined functions in Snowflake

### ISSUE THREAD

**Issue by pedromachados** [uber/h3-js#45]
The Snowflake data warehouse supports UDFs written in javascript. 

https://docs.snowflake.net/manuals/sql-reference/udf-js.html

I am not proficient in javascript but it seems to me that h3-js relies on the original C library. 

The key function I am interested in is `h3.geoToH3` but eventually, would like to add a few more.

Do you have any suggestions on how I may be able to create a pure javascript version of this function?

Thanks!

**Comment by nrabinowitz** [comment]
`h3-js` *is* pure JavaScript - we transpile the C library with Emscripten to create a JS version. So the library should be runnable anywhere you can use JS.

This is likely to be a blocker, though:
> All required code should be embedded within the UDF.

The code for `geoToH3` is non-trivial, and it looks like Snowflake would require you to inline the entire function. While this is possible, you'd basically have to manually port the entire function from C - I doubt you can use the Emscripten output.

So unfortunately this may be prohibitively hard.
