### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by helloniuniu** [uber/h3-js#48]
I have already read the H3(written by c). From your work, I knew that there are a variety of different ways to render H3 hexagons on a map. But I  don't know how to write an JavaScript program(html?) , can you give me a Demo?
Thank you very much! my email address:1160741941@qq.com

**Comment by nrabinowitz** [comment]
Please see the tutorials here for example Javascript implementations using Mapbox and H3: https://observablehq.com/collection/@nrabinowitz/h3-tutorial

I hope that helps!

**Comment by roiDaniela** [comment]
Hello @nrabinowitz 
Please forgive me if this isn't the right place to ask, but I am trying to add h3 hexagon layer to mapxbox using pure JS/Jquery code but haven't found a complete example. The hexagon's color is determined by the checkin inside it at the time of the last update

**Comment by nrabinowitz** [comment]
> Hello @nrabinowitz Please forgive me if this isn't the right place to ask, but I am trying to add h3 hexagon layer to mapxbox using pure JS/Jquery code but haven't found a complete example. The hexagon's color is determined by the checkin inside it at the time of the last update

Does this example work for you? https://observablehq.com/@nrabinowitz/h3-mapbox-style-heat-map

The approach here is to transform the H3 cells and data into GeoJSON, then render. This uses random data, but of course you can set the value according to some dataset. If you run into issues here, I'd encourage you to ask on StackOverflow with the `h3` tag.
