### ISSUE TITLE
h3ToGeoBoundary : documentation details

### ISSUE THREAD

**Issue by 1chandu** [uber/h3-js#50]
It seems `h3ToGeoBoundary` returns an array of vertices, that close the hexagon/pentagon/etc , i.e first and last vertices are same. When it is a hexagon it returns 7 vertices, where first and last are the same.  It will be helpful to clarify this in the documentation.

**Comment by nrabinowitz** [comment]
This is [documented here](https://github.com/uber/h3-js#module_h3.h3ToGeoBoundary) - the `formatAsGeoJson` param, if true, will provide closed loops (i.e. the start and end vertices are the same), as per the GeoJSON spec.
