### ISSUE TITLE
Geojson support

### ISSUE THREAD

**Issue by Portur** [uber/h3-js#59]
Hi,

Im trying to incorprate your library on a number of solutions which require realtime translations between hex ids and geojson multi/polygons.

```javascript 
h3.h3SetToMultiPolygon(["85291a6ffffffff"],true)
```
returns
```
[[[[-121.87310260648961,36.48355301296484],[-121.82059177712684,36.56646154014561],[-121.88144909358076,36.64149027277887],[-121.99481876336013,36.63355254199253],[-122.0471691328904,36.550641568925464],[-121.98631059624982,36.4756707384872],[-121.87310260648961,36.48355301296484]]]]
``` 

No problem with that. The issue however is displaying this now results in an askew/misrepresented polygon on a map.

![image](https://user-images.githubusercontent.com/24350810/62411171-841fd280-b5ef-11e9-8852-6743638186c4.png)

The map is in EPSG:4326. 
[Geojson.io](http://geojson.io)
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "color": "blue"
      },
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                -121.87310260648961,
                36.48355301296484
              ],
              [
                -121.82059177712684,
                36.56646154014561
              ],
              [
                -121.88144909358076,
                36.64149027277887
              ],
              [
                -121.99481876336013,
                36.63355254199253
              ],
              [
                -122.0471691328904,
                36.550641568925464
              ],
              [
                -121.98631059624982,
                36.4756707384872
              ],
              [
                -121.87310260648961,
                36.48355301296484
              ]
            ]
          ]
        ]
      }
    }
  ]
}
```

Is this correct?

**Comment by Portur** [comment]
Just to be clear, the expectation is an equal volume/shape hex [(such as this module by Turf)](http://turfjs.org/docs/#hexGrid)

**Comment by nrabinowitz** [comment]
This appears to be working as expected. In order to divide the world into stable cells that have low shape and area distortion, the H3 grid doesn't work like a screen-based or local hex binning algorithm with screen-aligned hexagons. 

Key issues to be aware of:

- The alignment of the cells will change in different parts of the world.
- Particularly at coarse resolutions, hexagons may appear distorted at northern or southern latitudes when shown on a Mercator projection (as in web maps). This is a function of the projection, not the H3 system.
- H3 cells are not exactly equal size or equal area, though they have low shape and area distortion.
- There are 12 pentagon-shaped cells at every resolution. These are centered in water, and can be ignored for many use cases.
- Some cells (on the edges of the icosahedron used to create the grid) are subject to distortion, which adds additional vertexes on one or two edges. Hexagon cells (in the topological sense, with 6 neighbors) may have up to eight vertices, and pentagon cells may have 10.

**Comment by Portur** [comment]
_see update below_

-----------------

Would a hex graticule not have zero distortion on a perfect sphere?

As I understand it, the hex grid allows for exact uniform distances between neighbouring cell distances, at a certain resolution, for n neighbours. If all hex polygons are askew as the one above, they won't sync up with a round trip of the earth. You won't end up where you started. Meaning a hex grid won't line up at the edges and poles. i.e. this diagram is thus incorrect

> - The alignment of the cells will change in different parts of the world.
> - Particularly at coarse resolutions, hexagons may appear distorted at northern or southern latitudes when shown on a Mercator projection (as in web maps). This is a function of the projection, not the H3 system.

This would only affect shrinking in the y-axis as you get closer to the poles, no?

> - H3 cells are not exactly equal size or equal area, though they have low shape and area distortion.

Maybe I misunderstand. I thought all cells are equal area/size/shape/orientation at a specific resolution.

> - There are 12 pentagon-shaped cells at every resolution. These are centered in water, and can be ignored for many use cases.

I'm not sure I follow here, how would a hex polygon over water differ from one on land? And as I understand these are hexagons, sevon of them if you count 1 parent and it's neighbours.

Update
---------------------------------------
Im leaving the above as this was my initial train of thought and my help others.

The hex grid is **_not_** calculated from a perfect sphere.

I went though the demonstrations and examples on observable. You are correct. I specifically chose the h3 index to avoid distortion but wasn't aware it was only minimized with h3, not avoided.

One of the videos clearly shows this.
![image](https://user-images.githubusercontent.com/24350810/62414009-bd1f6d80-b616-11e9-8172-cd52d7592e34.png)

And also showing the cases of areas over water vs land.
![image](https://user-images.githubusercontent.com/24350810/62414027-e63ffe00-b616-11e9-8533-432a5f03a3e6.png)

Thank for your answer(s)

**Comment by Portur** [comment]
More info [this gist](https://gist.github.com/anthonynorth/326235470e6b6b6d266dd611738b6377)

and [this video](https://www.youtube.com/watch?v=ay2uwtRO3QE)

**Comment by nrabinowitz** [comment]
H3 is based on a perfect sphere, but a sphere cannot be tiled with hexagons. This video goes into detail on the construction of the grid: https://youtu.be/wDuKeUkNLkQ

**Comment by curran** [comment]
I have a use case where the location on the globe does not matter, and one of my goals is to minimize the distortion of the hexagons.

Based on this screenshot in [https://github.com/uber/h3/issues/136](https://github.com/uber/h3/issues/136), I have determined _roughly_ the center point of one of those triangles to be (75.326508, 141.286197).

![image](https://user-images.githubusercontent.com/68416/127901470-00b1c463-6eb0-4911-9286-79f4ae66a1b4.png)
Original screenshot.

![image](https://user-images.githubusercontent.com/68416/127901577-dd284e90-64df-4f26-8850-721638542487.png)
Best guess location of triangle center.

My hexagons before, at (0,0):

![image](https://user-images.githubusercontent.com/68416/127901924-09d309cc-2bbb-48d3-acfb-37749048d98a.png)

My hexagons before, at (75.147338, 142.868226):

![image](https://user-images.githubusercontent.com/68416/127902573-897c4ba4-4ef2-4b21-b4de-b3aef82f99b4.png)

Finishing touch: rotate the projection by -2.4 degrees for vertical alignment:

![image](https://user-images.githubusercontent.com/68416/127902844-12645341-6997-4b20-856a-c07fbe9b2801.png)

If there is a way to find out the exact center of one of those triangles, I would be keen to know about it. I did a quick search through the codebase but was not able to locate where these geometries are defined.

**Comment by isaacbrodsky** [comment]
I don't think the library directly exposes this, but it should be possible to extract this from the library. The centroid of the triangle should be the centroid of the center cell on that face; in the C library this could be computed using internal functions as:

```
int res = 0;
for (int f = 0; f < NUM_ICOSA_FACES; f++) {
    FaceIJK fijk = {f, {0, 0, 0}};
    LatLng latLngRadians = {0, 0};
    _faceIjkToGeo(&fijk, res, &latLngRadians);
    // print latLngRadians
}
```

In order to do this from JavaScript you would need to get the H3 indexes these `FaceIJK`&res values represent and call `h3ToGeo`. If you need help getting those we can help get them.

**Comment by nrabinowitz** [comment]
See https://observablehq.com/@nrabinowitz/flat-h3-grid-via-gnomonic-projection

The `faceCenterGeo` has the center of each face.

**Comment by curran** [comment]
Amazing! Thank you so much 🙏

**Comment by Sulorb** [comment]
> 
> Finishing touch: rotate the projection by -2.4 degrees for vertical alignment:
> 
> ![image](https://user-images.githubusercontent.com/68416/127902844-12645341-6997-4b20-856a-c07fbe9b2801.png)
> 

How did you rotate the hexagons please? Mine are not perfectly aligned and i'd like it  like that.

**Comment by nrabinowitz** [comment]
@Sulorb This isn't likely to work in most cases, and it's just a visual adjustment, not a change to the grid. The H3 grid has fixed geographic positions, so if you'd like the cells in some area to be vertically aligned, you'd have to rotate the _map_, not the grid. The rotation you'd need would depend on your position on the globe, as different areas of the globe have differently aligned hexagon cells.

In general, if having perfectly aligned cells matters to your use case, H3 isn't a good fit - you'd be better off with an ad-hoc hex bin, such as those created by GIS software, or a visual hexbin like [the one Deck.gl provides](https://deck.gl/examples/hexagon-layer).
