### ISSUE TITLE
h3.h3SetToMultiPolygon - Confusing return values

### ISSUE THREAD

**Issue by chris-eaton** [uber/h3-js#71]
Hi

I am using h3 as means of generating a heatmap across a large map.  Currently the drawing aspect is a little slow (many thousands of hexagons).  So instead of drawing each hexagon separately I want to combine them using `h3.h3SetToMultiPolygon`.

I found it quite confusing to understand what the actual return is from this method.  But I attempted to draw using the return value as if it were a list of polygons. When I try to draw these polygons it fills in large areas.  Am I doing something wrong? Here is my code (typescript + google maps)

```
var megaPolygon = h3.h3SetToMultiPolygon(h3StringArray, false);

this.displayPolygons = [];

megaPolygon.forEach(polygon => {
    polygon.forEach(polygonLoop => {
        var newPath: ILatLngLiteral[] = [];

        polygonLoop.forEach(point => {
            newPath.push({
                latitude: point[0] as any,
                longitude: point[1] as any
            });
        });

        this.displayPolygons.push({
            id: this.displayPolygons.length,
            path: newPath,
            fill: {
                color: this.getHeatmapColor(0.7),
                opacity: 1
            },
            stroke: {
                weight: 0
            },
        });
    });
});
```

In these screenshots the top one is all individual hexagons, the bottom one is using `h3.h3SetToMultiPolygon`

Individual Hexes
![image](https://user-images.githubusercontent.com/12051582/65893433-d6873080-e39f-11e9-90b4-f5555b89806e.png)

MultiPolygon
![image](https://user-images.githubusercontent.com/12051582/65893529-fe769400-e39f-11e9-912b-93b49f8193f3.png)

If it helps, here is the raw data (as polylines)
![image](https://user-images.githubusercontent.com/12051582/65893579-13532780-e3a0-11e9-9b90-ac0134581d5d.png)

**Comment by nrabinowitz** [comment]
The issue here has nothing to do with H3, but rather the way you are constructing the polygons for Google maps. Is there no way to simply use GeoJSON input?

If I understand your code correctly, you are assuming all polygon loops are outer loops. They are not - only the first polygon loop is an outer loop. Subsequent loops are holes (this is following the GeoJSON spec). So what you're seeing is that holes in your polygon are being shown as filled polygons, rather than being excluded. I don't know how to exclude holes in the Google maps framework you're using - I'll leave it as an exercise for the reader :).

**Comment by chris-eaton** [comment]
Thanks for your pointers - I have it working now.

If it always returns a GeoJSON object why allow a flag to be passed into the function?

**Comment by chris-eaton** [comment]
To help anyone else who finds this question here is the code to make this work:
```
        var megaPolygon = h3.h3SetToMultiPolygon(h3StringArray, true);

        var data = {
            type: "FeatureCollection",
            features: [{
                "type": "Feature",
                geometry: {
                    "type": "MultiPolygon",
                    "coordinates": megaPolygon
                }
            }]
        };

        this.mapObject.data.addGeoJson(data);```

**Comment by nrabinowitz** [comment]
> If it always returns a GeoJSON object why allow a flag to be passed into the function?

By default, the C library returns polygons with `lat,lng` points and without repeating the first point as the last point. The flag switches this to `lng,lat` points and closes loops by repeating the first point at the end, per the GeoJSON spec.
