### ISSUE TITLE
is there a pre-bundled script in es5?

### ISSUE THREAD

**Issue by zuffenhausen** [uber/h3-js#72]
Is there an available [pre-bundled](https://unpkg.com/browse/h3-js@3.6.1/dist/) script transpiled to es5?  It's not clear to me what version the various `.js` files are.

I need an es5 version as I have a use case with Java 8 Nashorn (i.e. older).

**Comment by nrabinowitz** [comment]
It depends what the use case is.

- If you need an es5 CommonJS bundle for the browser, https://unpkg.com/browse/h3-js@3.6.1/dist/browser/h3-js.js will work best 
- If you want a UMD bundle for the browser (works with `require`, AMD loaders like `require.js`, and as a window-level global), then https://unpkg.com/browse/h3-js@3.6.1/dist/h3-js.umd.js is best 
- If you need CommonJS for Node, https://unpkg.com/browse/h3-js@3.6.1/dist/h3-js.js is best

I can try to clarify this in the docs.
