### ISSUE TITLE
3.6.2 polyfill breaking change from 3.5.0

### ISSUE THREAD

**Issue by Pessimistress** [uber/h3-js#76]
We previously used the following to generate all hexes at zoom 0:

```js
h3
  .polyfill([[-90, -180], [90, -180], [90, 0], [-90, 0]], 0)
  .concat(h3.polyfill([[-90, 180], [90, 180], [90, 0], [-90, 0]], 0))
```

When upgrading to 3.6.2 from 3.5.0, the above code returns an empty array.

**Comment by nrabinowitz** [comment]
We have a dedicated function for this: `h3.getRes0Indexes()`

Can you use this instead? I agree that the behavior here should probably be considered a regression, but `h3.getRes0Indexes()` will be more reliable and considerably faster in any case.

**Comment by wilsotc** [comment]
I'm seeing breaking changes with this function as well. At precision 2 I'm getting empty results. For instance:
h3.polyfill([[162, 72],[153, 72],[153, 81],[162, 81]], 2);
[]

**Comment by nrabinowitz** [comment]
We investigated in the core library and we're working on a fix. In the meantime, `3.6.3` rolls back to a slow-but-correct version of `polyfill` that should fix the issue until we have a faster version available.
