### ISSUE TITLE
h3IsValid returns true on invalid H3 indexes

### ISSUE THREAD

**Issue by Asa519** [uber/h3-js#79]
Hi, I have noticed that h3IsValid will return true for many indexes that are not actually valid. For example:
`h3IsValid("8a28308hello_world_ppppppppppppppppppqadjsadjasldajaskldlkjdklasjlk5505ffff")`
Returns true even though the string is clearly invalid. I think this is due to the calls to parseInt() in the h3IndexToSplitLong method:
```function h3IndexToSplitLong(h3Index) {
    if (typeof h3Index !== 'string') {
        return [0, 0];
    }
    const upper = parseInt(h3Index.substring(0, h3Index.length - 8), BASE_16);
    const lower = parseInt(h3Index.substring(h3Index.length - 8), BASE_16);
    return [lower, upper];
}
```
The first parseInt call will just ignore all of the extraneous characters in the middle of the string, only parsing "8a28308". This results in the above index being evaluated as equivalent to "8a283085505ffff".

**Comment by nrabinowitz** [comment]
Thanks for the report! Should be a simple fix, I'll see if I can get a PR up today.
