### ISSUE TITLE
Why is the node version limited to < 10?

### ISSUE THREAD

**Issue by allenan** [uber/h3-js#8]
The docs say it "can be used either in Node >= 4 or in the browser", but the package.json specifies node `< 10`.

```
"engines": {
    "node": ">=4 <10",
```

Just wondering if there's anything in the current version that breaks this library? or if the package.json is just being overly restrictive?

**Comment by nrabinowitz** [comment]
Honestly I think it's simply that we hadn't tested on 10. I can add a Travis test for this and update the engines.

**Comment by allenan** [comment]
@nrabinowitz have you had a chance to run the travis test on v10 yet?

**Comment by nrabinowitz** [comment]
Sorry for the delay on this - PR up.

**Comment by nrabinowitz** [comment]
Fixed and released in 3.0.2
