### ISSUE TITLE
Invalid left-hand side expression in prefix operation

### ISSUE THREAD

**Issue by supersonicclay** [uber/h3-js#85]
Getting an error attempting to load:
> Invalid left-hand side expression in prefix operation 

## Repro

https://codesandbox.io/s/h3-js-error-3murp

```
import React from 'react';
import ReactDOM from 'react-dom';
import h3 from "h3-js";

function App() {
  return <div>Hello world</div>
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by nrabinowitz** [comment]
Can you repro this outside of CodeSandbox? It's not an issue I've seen elsewhere, and I suspect it's a build issue in CodeSandbox rather than something specific to h3-js.

**Comment by supersonicclay** [comment]
Appears to be a CodeSandbox issue. I can't repro locally after downloading the CodeSandbox and running locally.

Created upstream issue: https://github.com/codesandbox/codesandbox-client/issues/4476

**Comment by nrabinowitz** [comment]
I think this likely specific to CodeSandbox, closing unless there's a repro I can address.
