### ISSUE TITLE
h3SetToMultiPolygon bug with duplicate hexagon indices

### ISSUE THREAD

**Issue by Pessimistress** [uber/h3-js#92]
To reproduce:

- Visit https://codepen.io/Pessimistress/pen/ZEWMmeB
- Uncomment line 7, which adds a duplicate hexagon index

Expected
![image](https://user-images.githubusercontent.com/2059298/93535023-0144fe80-f8fb-11ea-8cb6-52430a671637.png)

Actual
![image](https://user-images.githubusercontent.com/2059298/93535074-16ba2880-f8fb-11ea-8c92-ab7dc1d0e6dc.png)

**Comment by nrabinowitz** [comment]
At present, it's the responsibility of the caller to ensure that the indexes passed in are unique. Duplicate indexes, invalid indexes, or indexes at multiple resolutions result in undefined behavior. This is primarily a performance-based choice, as validating and de-duping the input set is potentially quite expensive, and is unnecessary if the input set is known to be valid by the caller.

This is not well-documented, though, so at a minimum we should add this warning to the docs.

**Comment by nrabinowitz** [comment]
It is documented on the main H3 site under `h3SetToLinkedGeo`: https://h3geo.org/#/documentation/api-reference/regions

But we should definitely document on `h3-js` as well.
